service: aggregate-service

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.environment.BUCKET_NAME}
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: BlockHeight
            AttributeType: N
        KeySchema:
          - AttributeName: BlockHeight
            KeyType: HASH
        ProvisionedThroughput: # Might need to turn on auto-scaling, default to 25 reads and writes for now.
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25

## Below is to run serverless against localstack
#plugins:
#  - serverless-localstack
#
#custom:
#  localstack:
#    stages:
#      - local
