# Sample serverless.yml used to create and deploy the necessary s3 bucket and dynamoDB tables

service: aggregate-service

provider:
  name: aws
  region: us-east-1

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: provenance-dw
    BlockBatchTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Aggregate-Service-Block-Batch
        AttributeDefinitions:
          - AttributeName: BatchId
            AttributeType: S
        KeySchema:
          - AttributeName: BatchId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 50
          WriteCapacityUnits: 50
    BlockMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Aggregate-Service-Block-Metadata
        AttributeDefinitions:
          - AttributeName: BlockHeight
            AttributeType: N
        KeySchema:
          - AttributeName: BlockHeight
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 300
          WriteCapacityUnits: 50
    ServiceMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Aggregate-Service-Metadata
        AttributeDefinitions:
          - AttributeName: Property
            AttributeType: S
        KeySchema:
          - AttributeName: Property
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 50
          WriteCapacityUnits: 50


## Below is to run serverless against localstack
#plugins:
#  - serverless-localstack
#
#custom:
#  localstack:
#    stages:
#      - local
