service: aggregate-service

provider:
  name: aws
  region: us-east-1

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aggregate-service-test-bucket
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: aggregateTable
        AttributeDefinitions:
          - AttributeName: blockHeight
            AttributeType: N
        KeySchema:
          - AttributeName: blockHeight
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


## Below is to run serverless against localstack
#plugins:
#  - serverless-localstack
#
#custom:
#  localstack:
#    stages:
#      - local
