service: aggregate-service

provider:
  name: aws
  region: us-east-1

custom:
  s3BucketName: ${file(env.yml):BUCKET_NAME}
  dynamoDbTableName: ${file(env.yml):DYNAMODB_TABLE_NAME}

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoDbTableName}
        AttributeDefinitions:
          - AttributeName: BlockHeight
            AttributeType: N
        KeySchema:
          - AttributeName: BlockHeight
            KeyType: HASH
        ProvisionedThroughput: # Might need to turn on auto-scaling, default to 25 reads and writes for now.
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25

## Below is to run serverless against localstack
#plugins:
#  - serverless-localstack
#
#custom:
#  localstack:
#    stages:
#      - local
