---
aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
  dynamodb:
    service-metadata-table: ${AWS_DYNAMODB_SERVICE_METADATA_TABLE_NAME}
    block-batch-table: ${AWS_DYNAMODB_BLOCK_BATCH_TABLE_NAME}
    block-metadata-table: ${AWS_DYNAMODB_BLOCK_METADATA_TABLE_NAME}

event-stream:
  websocket:
    uri: ${EVENT_STREAM_WEBSOCKET_URI}
    throttle-duration-ms: 0
  rpc:
    uri: ${EVENT_STREAM_RPC_URI}
  batch-size: 16
  filter:
    tx-events:
      - provenance.attribute.v1.EventAttributeAdd
      - provenance.attribute.v1.EventAttributeUpdate
      - provenance.attribute.v1.EventAttributeDelete
      - provenance.attribute.v1.EventAttributeDistinctDelete
      - provenance.marker.v1.EventMarkerActivate
      - provenance.marker.v1.EventMarkerAdd
      - provenance.marker.v1.EventMarkerBurn
      - provenance.marker.v1.EventMarkerCancel
      - provenance.marker.v1.EventMarkerDelete
      - provenance.marker.v1.EventMarkerFinalize
      - provenance.marker.v1.EventMarkerMint
      - provenance.marker.v1.EventMarkerSetDenomMetadata
      - provenance.marker.v1.EventMarkerTransfer
      - provenance.marker.v1.EventMarkerWithdraw
    # block-events:
    # - event1
    # - event2
    # ...

upload:
  extractors:
    - io.provenance.aggregate.service.stream.extractors.csv.impl.TxEventAttributes
    - io.provenance.aggregate.service.stream.extractors.csv.impl.TxMarkerTransfer
    - io.provenance.aggregate.service.stream.extractors.csv.impl.TxMarkerSupply
