ALTER TABLE ATTRIBUTES ADD IF NOT EXISTS uuid UUID;
ALTER TABLE ATTRIBUTES DROP CONSTRAINT attributes_pkey;
ALTER TABLE ATTRIBUTES ADD PRIMARY KEY (uuid);

ALTER TABLE COIN_TRANSFER ADD IF NOT EXISTS uuid UUID;
ALTER TABLE COIN_TRANSFER DROP CONSTRAINT coin_transfer_pkey;
ALTER TABLE COIN_TRANSFER ADD PRIMARY KEY (uuid);

ALTER TABLE FEES ADD IF NOT EXISTS uuid UUID;
ALTER TABLE FEES DROP CONSTRAINT fees_pkey;
ALTER TABLE FEES ADD PRIMARY KEY (uuid);

ALTER TABLE MARKER_SUPPLY ADD IF NOT EXISTS uuid UUID;
ALTER TABLE MARKER_SUPPLY DROP CONSTRAINT marker_supply_pkey;
ALTER TABLE MARKER_SUPPLY ADD PRIMARY KEY (uuid);

ALTER TABLE MARKER_TRANSFER ADD IF NOT EXISTS uuid UUID;
ALTER TABLE MARKER_TRANSFER DROP CONSTRAINT marker_transfer_pkey;
ALTER TABLE MARKER_TRANSFER ADD PRIMARY KEY (uuid);
