name: Build and Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS Config
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_TOKEN }} --secret ${{ secrets.AWS_SECRET_TOKEN }}
    - name: deploy serverless s3
      working-directory: ./
      run: sls deploy

